// Mock event data used as fallback when the backend is unavailable.
// Mirrors the shape returned by GET /events on the FastAPI backend so
// that the UI can render the same components against either source.
export const MOCK_EVENTS = [
  { id:1, country:"Ukraine", lat:48.38, lng:31.17, title:"Conflict Escalation in Eastern Regions", summary:"Intensified front-line operations with heavy drone and artillery activity. NATO supply routes under strain.", category:"war", region:"Europe", timestamp:"2025-03-18T06:30:00Z", assets:[{ symbol:"EUR/USD", direction:"down", pct:"0.4", reason:"Risk-off flight from EUR" },{ symbol:"NAT GAS", direction:"up", pct:"8.2", reason:"Pipeline disruption risk" },{ symbol:"WHEAT", direction:"up", pct:"3.4", reason:"Ukraine export blockade" },{ symbol:"LMT", direction:"up", pct:"4.2", reason:"Defense spending surge" }] },
  { id:2, country:"China", lat:35.86, lng:104.20, title:"PBOC Cuts Reserve Ratio 50bps", summary:"$140B liquidity injection targets slowing GDP. Manufacturing PMI below contraction threshold for 3rd month.", category:"economy", region:"Asia", timestamp:"2025-03-18T04:15:00Z", assets:[{ symbol:"USD/CNY", direction:"up", pct:"0.3", reason:"Yuan weakens on easing" },{ symbol:"COPPER", direction:"up", pct:"2.1", reason:"Demand outlook improves" },{ symbol:"IRON ORE", direction:"up", pct:"1.8", reason:"Construction stimulus bets" },{ symbol:"HSI", direction:"up", pct:"2.4", reason:"Liquidity drives equities" }] },
  { id:3, country:"United States", lat:37.09, lng:-95.71, title:"Fed Holds Rates — No Cut Through Q2", summary:"Powell signals higher-for-longer stance. Core PCE still 2.8%. Labor market adds 180k jobs vs 210k expected.", category:"economy", region:"Americas", timestamp:"2025-02-10T22:00:00Z", assets:[{ symbol:"DXY", direction:"up", pct:"0.6", reason:"Rate differential widens" },{ symbol:"EUR/USD", direction:"down", pct:"0.7", reason:"USD strengthens broadly" },{ symbol:"GOLD", direction:"down", pct:"0.9", reason:"Opportunity cost rises" },{ symbol:"QQQ", direction:"down", pct:"1.1", reason:"Growth stocks pressured" }] },
  { id:4, country:"Saudi Arabia", lat:23.89, lng:45.08, title:"OPEC+ Extends Cuts Through Q3", summary:"2.2M bpd reduction maintained. Riyadh targets $90 Brent floor ahead of sovereign wealth fund expansion.", category:"economy", region:"Middle East", timestamp:"2025-01-17T18:45:00Z", assets:[{ symbol:"BRENT", direction:"up", pct:"3.9", reason:"Supply reduction priced in" },{ symbol:"WTI", direction:"up", pct:"4.1", reason:"OPEC discipline holds" },{ symbol:"XOM", direction:"up", pct:"3.2", reason:"Margin expansion for majors" },{ symbol:"USD/SAR", direction:"flat", pct:"0.0", reason:"Peg maintained by CB" }] },
  { id:5, country:"Taiwan", lat:23.70, lng:120.96, title:"PLA Exercises Escalate in Taiwan Strait", summary:"Largest naval drill in 18 months. 45 PLA aircraft crossed median line. US carrier group repositioned.", category:"war", region:"Asia", timestamp:"2024-12-17T12:00:00Z", assets:[{ symbol:"TSM", direction:"down", pct:"3.8", reason:"Fab disruption risk priced" },{ symbol:"SOX", direction:"down", pct:"2.1", reason:"Supply chain uncertainty" },{ symbol:"GOLD", direction:"up", pct:"1.4", reason:"Safe haven bid surges" },{ symbol:"USD/TWD", direction:"up", pct:"1.1", reason:"TWD weakens on tension" }] },
  { id:6, country:"Germany", lat:51.17, lng:10.45, title:"Germany Enters Technical Recession", summary:"Q4 GDP -0.3%, second consecutive contraction. IFO business climate at 2-year low. Bunds rally.", category:"economy", region:"Europe", timestamp:"2024-09-16T09:00:00Z", assets:[{ symbol:"EUR/USD", direction:"down", pct:"0.9", reason:"Eurozone growth anchor drags" },{ symbol:"DAX", direction:"down", pct:"1.8", reason:"Corporate earnings cut" },{ symbol:"BUND 10Y", direction:"up", pct:"0.8", reason:"ECB cut bets accelerate" },{ symbol:"EUR/GBP", direction:"down", pct:"0.6", reason:"GBP outperforms EUR" }] },
  { id:7, country:"Iran", lat:32.43, lng:53.69, title:"US Sanctions Hit Iranian Energy Sector", summary:"Treasury targets 15 entities and 3 tankers. Hormuz transit insurance premiums spike 40%.", category:"politics", region:"Middle East", timestamp:"2024-03-15T16:30:00Z", assets:[{ symbol:"BRENT", direction:"up", pct:"2.3", reason:"Supply shock risk premium" },{ symbol:"SHIPPING", direction:"up", pct:"4.5", reason:"Rerouting adds cost/time" },{ symbol:"USD/IRR", direction:"up", pct:"3.2", reason:"IRR depreciates sharply" },{ symbol:"FRO", direction:"up", pct:"3.1", reason:"Tanker rates benefit" }] },
  { id:8, country:"Japan", lat:36.20, lng:138.25, title:"BOJ Ends Negative Rate Policy", summary:"First rate hike in 17 years. Policy rate lifted to 0.1%. ¥15T carry trade unwind begins.", category:"economy", region:"Asia", timestamp:"2023-03-14T03:00:00Z", assets:[{ symbol:"USD/JPY", direction:"down", pct:"2.8", reason:"JPY surges on normalization" },{ symbol:"NIKKEI", direction:"down", pct:"2.1", reason:"Exporters hit by strong JPY" },{ symbol:"JP BANKS", direction:"up", pct:"5.3", reason:"NIM expansion incoming" },{ symbol:"JGB 10Y", direction:"down", pct:"1.4", reason:"Yields rise, prices fall" }] },
];
